feat: 파일 다운로드 시 contentDisposition의 값이 빈문자열일 경우 프로세스 종료
classtinginc/react-native-webview pull request #28
Opened 2023-05-31 09:40 UTC by shhong7757

contentDisposition 값을 사용해 파일 이름, 확장자명을 추출하고있기 때문에
빈문자열일 때 에러가 발생

빈문자열일 때 프로세스를 종료하도록 하여 예상치 않은 일이 발생해도 앱이
종료되지 않도록 함

2023-05-31 10:00 UTC, leegeunhyeok requested changes

2023-05-31 10:00 UTC, leegeunhyeok commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
> +          if (fileName == "") {
자바라서 아래처럼 처리하도록 수정해야 할 거 같습니다

```suggestion
          if (fileName.equals("")) {
```

2023-05-31 10:08 UTC, shhong7757 commented
## Changes
- 문자열 비교를 위해 equals 메소드 사용하도록 수정

2023-05-31 10:08 UTC, shhong7757 commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
> +          if (fileName == "") {
제안해주신 방법으로 수정했습니다. 감사합니다.

2023-05-31 10:11 UTC, ujeon approved these changes

2023-05-31 10:12 UTC, leegeunhyeok approved these changes

2023-05-31 10:34 UTC, merged

2023-07-12 04:19 UTC, leegeunhyeok commented
https://github.com/classtinginc/classting-rn/pull/5525